"""glTF export and the sidecar JSON.

Coordinates. Blender is Z-up with the model facing -Y. The glTF exporter
(`export_yup=True`) maps Blender (x, y, z) to glTF (x, z, -y), so the model faces
glTF +Z, the glTF convention. Bevy's forward is -Z, and its glTF loader does no
conversion by default, so the Rust spawn helper (`models::spawn_model`) rotates
every model 180 degrees about +Y: glTF (x, y, z) -> (-x, y, -z). Net effect:

    Blender (x, y, z)  ->  Bevy model space (-x, z, y)

That map is a proper rotation (determinant +1), so rotations convert as
R_bevy = M R_blender M^T with M = [[-1, 0, 0], [0, 0, 1], [0, 1, 0]].

The sidecar is written in Bevy model space: metres, +Y up, -Z forward (the
model's front), +X to the model's right, relative to the model root (on the
ground at the origin). Rust reads it as-is; no further conversion.
"""

import json
import math
import os

import bpy
from mathutils import Matrix, Vector

from . import palette as pal
from . import scene, shapes

BLENDER_TO_BEVY = Matrix(((-1.0, 0.0, 0.0), (0.0, 0.0, 1.0), (0.0, 1.0, 0.0)))

SPACE_DOC = ("Bevy model space after models::spawn_model's forward fix: metres, +Y up, "
             "-Z forward (the model's front), +X right, origin at the model root on the ground. "
             "Blender (x, y, z) -> (-x, z, y).")


def to_bevy(v):
    return Vector((-v.x, v.z, v.y))


def rotation_to_bevy(quat):
    m = BLENDER_TO_BEVY @ quat.to_matrix() @ BLENDER_TO_BEVY.transposed()
    return m.to_quaternion()


def _num(x, places=4):
    v = round(float(x), places)
    return 0.0 if v == 0 else v  # no "-0.0" in the JSON


def _vec(v):
    return [_num(c) for c in v]


def export_glb(root, path):
    """Exports root and its descendants to a .glb (vertex colours as COLOR_0)."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    for obj in bpy.context.scene.objects:
        obj.select_set(False)
    objs = [root] + scene.descendants(root)
    for obj in objs:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = root
    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format="GLB",
        use_selection=True,
        export_apply=True,
        export_yup=True,
        export_extras=True,
        export_vertex_color="ACTIVE",
        export_all_vertex_colors=False,
        export_active_vertex_color_when_no_material=True,
        export_attributes=False,
        export_texcoords=False,
        export_normals=True,
        export_tangents=False,
        export_materials="EXPORT",
        export_cameras=False,
        export_lights=False,
        export_animations=False,
        export_skins=False,
        export_morph=False,
        export_copyright="Pieced (original, generated by art/blender)",
    )


def bounds_of(points):
    lo = Vector((min(p.x for p in points), min(p.y for p in points), min(p.z for p in points)))
    hi = Vector((max(p.x for p in points), max(p.y for p in points), max(p.z for p in points)))
    return lo, hi


def sidecar(root, kind, source, budget, colors_by_part):
    """The sidecar dict: per-part bounds and triangles, attach points, totals."""
    scene.update()
    parts = {}
    attach = {}
    all_points = []
    total = 0
    for obj in scene.descendants(root):
        parent = obj.parent.name if obj.parent is not None else None
        if obj.type == "MESH":
            mw = obj.matrix_world
            pts = [to_bevy(mw @ v.co) for v in obj.data.vertices]
            lo, hi = bounds_of(pts)
            tris = shapes.triangles(obj)
            total += tris
            all_points += [lo, hi]
            parts[obj.name] = {
                "parent": parent,
                "bounds": {"min": _vec(lo), "max": _vec(hi)},
                "triangles": tris,
                "colors": colors_by_part.get(obj.name, []),
            }
        elif obj.type == "EMPTY":
            loc, rot, _ = obj.matrix_world.decompose()
            q = rotation_to_bevy(rot)
            attach[obj.name] = {
                "parent": parent,
                "position": _vec(to_bevy(loc)),
                "rotation": [_num(q.x, 6), _num(q.y, 6), _num(q.z, 6), _num(q.w, 6)],
            }
    if not parts:
        raise ValueError(f"{root.name}: no mesh parts")
    lo, hi = bounds_of(all_points)
    return {
        "name": root.name,
        "kind": kind,
        "source": source,
        "space": SPACE_DOC,
        "triangles": total,
        "triangle_budget": budget,
        "bounds": {"min": _vec(lo), "max": _vec(hi)},
        "parts": dict(sorted(parts.items())),
        "attach": dict(sorted(attach.items())),
    }


def write_json(data, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")


def finish_meshes(root):
    """Bakes palette tags to COLOR_0 and gives every mesh the shared export material.

    Returns {part name: [palette colour names used]}.
    """
    mat = pal.export_material()
    used = {}
    for obj in scene.descendants(root):
        if obj.type != "MESH":
            continue
        used[obj.name] = pal.bake_colors(obj)
        obj.data.materials.clear()
        obj.data.materials.append(mat)
        if not all(math.isfinite(c) for v in obj.data.vertices for c in v.co):
            raise ValueError(f"{obj.name}: non-finite vertex positions")
    return used
