#!/usr/bin/env python3
"""Mirrors art/palette.json into `palette::cartoon` in src/palette.rs.

    python3 art/tools/palette_to_rust.py            # print the Rust block
    python3 art/tools/palette_to_rust.py --write    # replace the block in src/palette.rs
    python3 art/tools/palette_to_rust.py --check    # exit 1 if src/palette.rs is stale

The block sits between the BEGIN/END marker comments; everything else in
src/palette.rs is left alone. A unit test in the block fails if the consts and
art/palette.json ever disagree.
"""

import json
import os
import sys

REPO = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
PALETTE = os.path.join(REPO, "art", "palette.json")
TARGET = os.path.join(REPO, "src", "palette.rs")
BEGIN = "// BEGIN cartoon palette (generated by art/tools/palette_to_rust.py; do not edit by hand)"
END = "// END cartoon palette"


def block():
    with open(PALETTE) as f:
        palette = json.load(f)
    lines = [
        BEGIN,
        "",
        "/// The Milestone 2 cartoon palette, sampled from the target images",
        "/// (`art/tools/palette_samples.json`). `art/palette.json` is the source of",
        "/// truth; these consts mirror it. Models carry the lit colours as glTF",
        "/// `COLOR_0`; each `*_SHADOW` is the targets' shadow band for that surface.",
        "/// Values are sRGB.",
        "pub mod cartoon {",
        "    use super::rgb;",
        "    use bevy::color::Color;",
        "",
    ]
    for name in sorted(palette):
        h = palette[name].lstrip("#")
        r, g, b = h[0:2], h[2:4], h[4:6]
        lines.append(f"    pub const {name.upper()}: Color = rgb(0x{r}, 0x{g}, 0x{b});")
    lines += [
        "",
        "    /// Every colour by its `art/palette.json` name.",
        "    pub const ALL: &[(&str, Color)] = &[",
    ]
    for name in sorted(palette):
        lines.append(f'        ("{name}", {name.upper()}),')
    lines += [
        "    ];",
        "",
        "    /// Looks a colour up by its palette name.",
        "    pub fn by_name(name: &str) -> Option<Color> {",
        "        ALL.iter().find(|(n, _)| *n == name).map(|(_, c)| *c)",
        "    }",
        "",
        "    #[cfg(test)]",
        "    mod tests {",
        "        use super::ALL;",
        "        use std::collections::BTreeMap;",
        "",
        "        fn hex(c: bevy::color::Color) -> String {",
        "            let s = c.to_srgba();",
        "            let b = |v: f32| (v * 255.0).round() as u8;",
        '            format!("#{:02X}{:02X}{:02X}", b(s.red), b(s.green), b(s.blue))',
        "        }",
        "",
        "        #[test]",
        "        fn consts_match_art_palette_json() {",
        "            let json: BTreeMap<String, String> =",
        '                serde_json::from_str(include_str!("../art/palette.json")).unwrap();',
        "            let consts: BTreeMap<String, String> =",
        "                ALL.iter().map(|(n, c)| (n.to_string(), hex(*c))).collect();",
        "            let json: BTreeMap<String, String> = json",
        "                .into_iter()",
        "                .map(|(n, h)| (n, h.to_uppercase()))",
        "                .collect();",
        "            assert_eq!(",
        "                consts, json,",
        '                "palette::cartoon is stale: run python3 art/tools/palette_to_rust.py --write"',
        "            );",
        "        }",
        "    }",
        "}",
        "",
        END,
    ]
    return "\n".join(lines) + "\n"


def spliced(current):
    new = block()
    if BEGIN in current:
        head = current[:current.index(BEGIN)]
        tail = current[current.index(END) + len(END):].lstrip("\n")
        return head + new + (("\n" + tail) if tail else "")
    return current.rstrip("\n") + "\n\n" + new


def main():
    arg = sys.argv[1] if len(sys.argv) > 1 else ""
    if arg == "--write":
        with open(TARGET) as f:
            current = f.read()
        with open(TARGET, "w") as f:
            f.write(spliced(current))
        print(f"wrote palette::cartoon to {os.path.relpath(TARGET, REPO)}")
    elif arg == "--check":
        with open(TARGET) as f:
            current = f.read()
        if spliced(current) != current:
            print("src/palette.rs is stale: run python3 art/tools/palette_to_rust.py --write")
            sys.exit(1)
    else:
        sys.stdout.write(block())


main()
