//! The art direction's palette (docs/SPEC.md → Art direction). Every slice takes
//! colors from here so the world reads as one design. Values are sRGB.

use bevy::color::Color;

const fn rgb(r: u8, g: u8, b: u8) -> Color {
    Color::srgb(r as f32 / 255.0, g as f32 / 255.0, b as f32 / 255.0)
}

// Sky and atmosphere: warm late afternoon.
pub const SKY_ZENITH: Color = rgb(0x5E, 0x9C, 0xE0);
pub const SKY_HORIZON: Color = rgb(0xF6, 0xD3, 0x9C);
/// Pale clear blue between the gold horizon and the zenith (avoids a muddy blend).
pub const SKY_MID: Color = rgb(0xA8, 0xCC, 0xEE);
pub const SUN_DISC: Color = rgb(0xFF, 0xF1, 0xC8);
pub const SUNLIGHT: Color = rgb(0xFF, 0xE6, 0xBF);
pub const FOG: Color = rgb(0xEE, 0xD2, 0xA8);
pub const AMBIENT: Color = rgb(0xC9, 0xD8, 0xF0);
/// Cool skylight fill from above (no shadows): keeps shadowed faces shaped.
pub const SKYLIGHT: Color = rgb(0xB8, 0xCF, 0xF2);
/// Warm-neutral bounce used as the ambient term.
pub const BOUNCE: Color = rgb(0xE6, 0xE0, 0xD8);

// Muted mid-tone world.
pub const GRASS: Color = rgb(0x8C, 0x9E, 0x62);
pub const GRASS_DARK: Color = rgb(0x6F, 0x84, 0x4E);
pub const OLIVE: Color = rgb(0x7A, 0x7F, 0x4C);
pub const SAND: Color = rgb(0xD9, 0xC2, 0x93);
pub const ROCK: Color = rgb(0x7E, 0x82, 0x8C);
pub const ROCK_DARK: Color = rgb(0x5F, 0x63, 0x6E);
pub const FOLIAGE: Color = rgb(0x5E, 0x7D, 0x4A);
pub const TRUNK: Color = rgb(0x6B, 0x4E, 0x38);
pub const FOLIAGE_LIGHT: Color = rgb(0x7D, 0x98, 0x58);
pub const SAGE: Color = rgb(0xA3, 0xAE, 0x86);
pub const DIRT: Color = rgb(0xB4, 0xA2, 0x7E);
pub const ROCK_LIGHT: Color = rgb(0x9C, 0x9E, 0xA6);
pub const ROCK_WARM: Color = rgb(0x8F, 0x87, 0x7D);
pub const MESA: Color = rgb(0xC9, 0x8E, 0x66);
pub const MESA_DARK: Color = rgb(0xA8, 0x70, 0x52);
pub const CLOUD: Color = rgb(0xFF, 0xF8, 0xEE);
pub const CLOUD_SHADE: Color = rgb(0xF0, 0xD4, 0xCB);

// Player-built pieces: warm crafted wood, clearly brighter than the ground.
pub const WOOD: Color = rgb(0xE0, 0xA9, 0x62);
pub const WOOD_LIGHT: Color = rgb(0xF0, 0xC4, 0x84);
pub const WOOD_DARK: Color = rgb(0xB9, 0x7D, 0x3F);
pub const WOOD_TRIM: Color = rgb(0x9A, 0x64, 0x32);
pub const GHOST_VALID: Color = Color::srgba(0.55, 0.85, 1.0, 0.35);
pub const GHOST_INVALID: Color = Color::srgba(1.0, 0.35, 0.3, 0.35);

// The target: one saturated hue used nowhere else, plus its rim light.
pub const TARGET: Color = rgb(0xFF, 0x4F, 0x7B);
pub const TARGET_DARK: Color = rgb(0xC2, 0x2E, 0x5A);
pub const TARGET_RIM: Color = rgb(0xFF, 0xC2, 0xD4);
/// Bullseye rings on the dummy's target plates.
pub const TARGET_LIGHT: Color = rgb(0xFF, 0xE4, 0xEC);

// Guns (viewmodel).
pub const GUN_METAL: Color = rgb(0x3C, 0x41, 0x4A);
pub const GUN_POLYMER: Color = rgb(0x2B, 0x2E, 0x33);
pub const GUN_ACCENT: Color = rgb(0xD8, 0x9A, 0x4E);

// Feedback and UI.
pub const SHIELD: Color = rgb(0x59, 0xB8, 0xFF);
pub const HEALTH: Color = rgb(0x7B, 0xE0, 0x6A);
pub const HIT_WHITE: Color = rgb(0xFF, 0xFF, 0xFF);
pub const HEADSHOT: Color = rgb(0xFF, 0xD2, 0x3F);
pub const MUZZLE: Color = rgb(0xFF, 0xD9, 0x8A);
pub const UI_TEXT: Color = rgb(0xF7, 0xF3, 0xEA);
pub const UI_SHADOW: Color = Color::srgba(0.05, 0.05, 0.08, 0.6);
pub const UI_PANEL: Color = Color::srgba(0.08, 0.09, 0.12, 0.55);

// BEGIN cartoon palette (generated by art/tools/palette_to_rust.py; do not edit by hand)

/// The Milestone 2 cartoon palette, sampled from the target images
/// (`art/tools/palette_samples.json`). `art/palette.json` is the source of
/// truth; these consts mirror it. Models carry the lit colours as glTF
/// `COLOR_0`; each `*_SHADOW` is the targets' shadow band for that surface.
/// Values are sRGB.
pub mod cartoon {
    use super::rgb;
    use bevy::color::Color;

    pub const BARRIER_CYAN: Color = rgb(0xA7, 0xE5, 0xFD);
    pub const BRASS: Color = rgb(0xC8, 0x93, 0x4E);
    pub const BRASS_SHADOW: Color = rgb(0x70, 0x4E, 0x23);
    pub const BRICK: Color = rgb(0xC6, 0x67, 0x48);
    pub const BRICK_SHADOW: Color = rgb(0x85, 0x48, 0x3B);
    pub const CLIFF_DIRT: Color = rgb(0xA6, 0x7E, 0x6F);
    pub const CLIFF_DIRT_SHADOW: Color = rgb(0x6E, 0x5E, 0x68);
    pub const CLOUD: Color = rgb(0xAB, 0xB8, 0xF8);
    pub const CRYSTAL_BLUE: Color = rgb(0x4D, 0xD0, 0xFD);
    pub const CRYSTAL_VIOLET: Color = rgb(0x9C, 0x52, 0xDA);
    pub const EYE_WHITE: Color = rgb(0xFF, 0xFF, 0xCE);
    pub const FOLIAGE: Color = rgb(0x65, 0x97, 0x40);
    pub const FOLIAGE_SHADOW: Color = rgb(0x2A, 0x69, 0x5C);
    pub const GALAXY_DEEP: Color = rgb(0x5E, 0x77, 0xDD);
    pub const GALAXY_PURPLE: Color = rgb(0x83, 0x6D, 0xE4);
    pub const GALAXY_TEAL: Color = rgb(0x5F, 0xEB, 0xF4);
    pub const GHOST_BLUE: Color = rgb(0x69, 0xA4, 0xFD);
    pub const GHOST_RED: Color = rgb(0xFF, 0x6A, 0x7D);
    pub const GLASS_CYAN: Color = rgb(0x97, 0xC8, 0xE2);
    pub const GLASS_PINK: Color = rgb(0xD8, 0xA0, 0xBD);
    pub const GLASS_VIOLET: Color = rgb(0xD8, 0x8E, 0xD6);
    pub const GLASS_YELLOW: Color = rgb(0xF2, 0xC9, 0x86);
    pub const GLOVE_WHITE: Color = rgb(0xF6, 0xEB, 0xDE);
    pub const GLOVE_WHITE_SHADOW: Color = rgb(0xC5, 0xBE, 0xCF);
    pub const GOLD_RINGS: Color = rgb(0xC1, 0x7E, 0x2A);
    pub const GRASS: Color = rgb(0x7A, 0xAE, 0x49);
    pub const GRASS_SHADOW: Color = rgb(0x51, 0x7A, 0x38);
    pub const GRID_LINE: Color = rgb(0xE4, 0xFF, 0xF5);
    pub const GUN_IRON: Color = rgb(0x3C, 0x3E, 0x56);
    pub const HUD_FRAME: Color = rgb(0x75, 0x87, 0x96);
    pub const HUD_HEALTH: Color = rgb(0x4B, 0xFB, 0x56);
    pub const HUD_PANEL: Color = rgb(0x16, 0x23, 0x35);
    pub const HUD_SHIELD: Color = rgb(0x0D, 0xBB, 0xFE);
    pub const INK: Color = rgb(0x02, 0x04, 0x02);
    pub const KNIGHT_PURPLE: Color = rgb(0x72, 0x2F, 0x9F);
    pub const KNIGHT_PURPLE_SHADOW: Color = rgb(0x43, 0x17, 0x6F);
    pub const KNIGHT_STEEL: Color = rgb(0x82, 0x82, 0x96);
    pub const KNIGHT_STEEL_SHADOW: Color = rgb(0x57, 0x5D, 0x76);
    pub const MORTAR: Color = rgb(0xBA, 0xA7, 0x9D);
    pub const MORTAR_SHADOW: Color = rgb(0x78, 0x71, 0x82);
    pub const NAIL_HEAD: Color = rgb(0x84, 0x83, 0x9A);
    pub const PLANET_VIOLET: Color = rgb(0x7B, 0x87, 0xDD);
    pub const PLANK: Color = rgb(0x9F, 0x6E, 0x46);
    pub const PLANK_SHADOW: Color = rgb(0x6E, 0x48, 0x33);
    pub const PUPIL_BLACK: Color = rgb(0x00, 0x00, 0x00);
    pub const ROCK: Color = rgb(0xB8, 0xA2, 0x9F);
    pub const ROCK_SHADOW: Color = rgb(0x61, 0x65, 0x89);
    pub const SHIELD_CYAN: Color = rgb(0x73, 0xC4, 0xFB);
    pub const SPELL_BLUE: Color = rgb(0x38, 0x85, 0xFC);
    pub const SPELL_GOLD: Color = rgb(0xF9, 0xDD, 0x4E);
    pub const SPELL_VIOLET: Color = rgb(0xC0, 0x7B, 0xD5);
    pub const STAR_GOLD: Color = rgb(0xF4, 0xC2, 0x60);
    pub const STATION_STONE: Color = rgb(0x67, 0x70, 0x93);
    pub const STATION_STONE_SHADOW: Color = rgb(0x51, 0x5D, 0x8C);
    pub const STOCK: Color = rgb(0x86, 0x45, 0x35);
    pub const STOCK_SHADOW: Color = rgb(0x55, 0x2D, 0x2B);
    pub const STUMP_BARK: Color = rgb(0x9F, 0x65, 0x3D);
    pub const STUMP_BARK_LINE: Color = rgb(0x51, 0x37, 0x28);
    pub const STUMP_BARK_SHADOW: Color = rgb(0x55, 0x3B, 0x39);
    pub const STUMP_RING_LINE: Color = rgb(0xB1, 0x81, 0x4B);
    pub const STUMP_RINGS: Color = rgb(0xCF, 0x98, 0x5C);
    pub const STUMP_RINGS_SHADOW: Color = rgb(0x87, 0x69, 0x50);
    pub const TRUNK: Color = rgb(0xB6, 0x75, 0x45);
    pub const TRUNK_SHADOW: Color = rgb(0x7E, 0x54, 0x3D);
    pub const TUFT: Color = rgb(0x6D, 0xA9, 0x3D);
    pub const WATERFALL_BLUE: Color = rgb(0x90, 0xCA, 0xFD);

    /// Every colour by its `art/palette.json` name.
    pub const ALL: &[(&str, Color)] = &[
        ("barrier_cyan", BARRIER_CYAN),
        ("brass", BRASS),
        ("brass_shadow", BRASS_SHADOW),
        ("brick", BRICK),
        ("brick_shadow", BRICK_SHADOW),
        ("cliff_dirt", CLIFF_DIRT),
        ("cliff_dirt_shadow", CLIFF_DIRT_SHADOW),
        ("cloud", CLOUD),
        ("crystal_blue", CRYSTAL_BLUE),
        ("crystal_violet", CRYSTAL_VIOLET),
        ("eye_white", EYE_WHITE),
        ("foliage", FOLIAGE),
        ("foliage_shadow", FOLIAGE_SHADOW),
        ("galaxy_deep", GALAXY_DEEP),
        ("galaxy_purple", GALAXY_PURPLE),
        ("galaxy_teal", GALAXY_TEAL),
        ("ghost_blue", GHOST_BLUE),
        ("ghost_red", GHOST_RED),
        ("glass_cyan", GLASS_CYAN),
        ("glass_pink", GLASS_PINK),
        ("glass_violet", GLASS_VIOLET),
        ("glass_yellow", GLASS_YELLOW),
        ("glove_white", GLOVE_WHITE),
        ("glove_white_shadow", GLOVE_WHITE_SHADOW),
        ("gold_rings", GOLD_RINGS),
        ("grass", GRASS),
        ("grass_shadow", GRASS_SHADOW),
        ("grid_line", GRID_LINE),
        ("gun_iron", GUN_IRON),
        ("hud_frame", HUD_FRAME),
        ("hud_health", HUD_HEALTH),
        ("hud_panel", HUD_PANEL),
        ("hud_shield", HUD_SHIELD),
        ("ink", INK),
        ("knight_purple", KNIGHT_PURPLE),
        ("knight_purple_shadow", KNIGHT_PURPLE_SHADOW),
        ("knight_steel", KNIGHT_STEEL),
        ("knight_steel_shadow", KNIGHT_STEEL_SHADOW),
        ("mortar", MORTAR),
        ("mortar_shadow", MORTAR_SHADOW),
        ("nail_head", NAIL_HEAD),
        ("planet_violet", PLANET_VIOLET),
        ("plank", PLANK),
        ("plank_shadow", PLANK_SHADOW),
        ("pupil_black", PUPIL_BLACK),
        ("rock", ROCK),
        ("rock_shadow", ROCK_SHADOW),
        ("shield_cyan", SHIELD_CYAN),
        ("spell_blue", SPELL_BLUE),
        ("spell_gold", SPELL_GOLD),
        ("spell_violet", SPELL_VIOLET),
        ("star_gold", STAR_GOLD),
        ("station_stone", STATION_STONE),
        ("station_stone_shadow", STATION_STONE_SHADOW),
        ("stock", STOCK),
        ("stock_shadow", STOCK_SHADOW),
        ("stump_bark", STUMP_BARK),
        ("stump_bark_line", STUMP_BARK_LINE),
        ("stump_bark_shadow", STUMP_BARK_SHADOW),
        ("stump_ring_line", STUMP_RING_LINE),
        ("stump_rings", STUMP_RINGS),
        ("stump_rings_shadow", STUMP_RINGS_SHADOW),
        ("trunk", TRUNK),
        ("trunk_shadow", TRUNK_SHADOW),
        ("tuft", TUFT),
        ("waterfall_blue", WATERFALL_BLUE),
    ];

    /// Looks a colour up by its palette name.
    pub fn by_name(name: &str) -> Option<Color> {
        ALL.iter().find(|(n, _)| *n == name).map(|(_, c)| *c)
    }

    #[cfg(test)]
    mod tests {
        use super::ALL;
        use std::collections::BTreeMap;

        fn hex(c: bevy::color::Color) -> String {
            let s = c.to_srgba();
            let b = |v: f32| (v * 255.0).round() as u8;
            format!("#{:02X}{:02X}{:02X}", b(s.red), b(s.green), b(s.blue))
        }

        #[test]
        fn consts_match_art_palette_json() {
            let json: BTreeMap<String, String> =
                serde_json::from_str(include_str!("../art/palette.json")).unwrap();
            let consts: BTreeMap<String, String> =
                ALL.iter().map(|(n, c)| (n.to_string(), hex(*c))).collect();
            let json: BTreeMap<String, String> = json
                .into_iter()
                .map(|(n, h)| (n, h.to_uppercase()))
                .collect();
            assert_eq!(
                consts, json,
                "palette::cartoon is stale: run python3 art/tools/palette_to_rust.py --write"
            );
        }
    }
}

// END cartoon palette
